// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: repo.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRepoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Owner         string                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Repo          string                 `protobuf:"bytes,2,opt,name=repo,proto3" json:"repo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoRequest) Reset() {
	*x = GetRepoRequest{}
	mi := &file_repo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoRequest) ProtoMessage() {}

func (x *GetRepoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoRequest.ProtoReflect.Descriptor instead.
func (*GetRepoRequest) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{0}
}

func (x *GetRepoRequest) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *GetRepoRequest) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type GetRepoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Creator       string                 `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	StarsCnt      int32                  `protobuf:"varint,4,opt,name=stars_cnt,json=starsCnt,proto3" json:"stars_cnt,omitempty"`
	ForksCnt      int32                  `protobuf:"varint,5,opt,name=forks_cnt,json=forksCnt,proto3" json:"forks_cnt,omitempty"`
	IssuesCnt     int32                  `protobuf:"varint,6,opt,name=issues_cnt,json=issuesCnt,proto3" json:"issues_cnt,omitempty"`
	Lang          string                 `protobuf:"bytes,7,opt,name=lang,proto3" json:"lang,omitempty"`
	Size          int32                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	License       string                 `protobuf:"bytes,10,opt,name=license,proto3" json:"license,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRepoResponse) Reset() {
	*x = GetRepoResponse{}
	mi := &file_repo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRepoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRepoResponse) ProtoMessage() {}

func (x *GetRepoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_repo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRepoResponse.ProtoReflect.Descriptor instead.
func (*GetRepoResponse) Descriptor() ([]byte, []int) {
	return file_repo_proto_rawDescGZIP(), []int{1}
}

func (x *GetRepoResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetRepoResponse) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *GetRepoResponse) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *GetRepoResponse) GetStarsCnt() int32 {
	if x != nil {
		return x.StarsCnt
	}
	return 0
}

func (x *GetRepoResponse) GetForksCnt() int32 {
	if x != nil {
		return x.ForksCnt
	}
	return 0
}

func (x *GetRepoResponse) GetIssuesCnt() int32 {
	if x != nil {
		return x.IssuesCnt
	}
	return 0
}

func (x *GetRepoResponse) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *GetRepoResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GetRepoResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetRepoResponse) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

var File_repo_proto protoreflect.FileDescriptor

const file_repo_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"repo.proto\x12\x04repo\":\n" +
	"\x0eGetRepoRequest\x12\x14\n" +
	"\x05owner\x18\x01 \x01(\tR\x05owner\x12\x12\n" +
	"\x04repo\x18\x02 \x01(\tR\x04repo\"\x8f\x02\n" +
	"\x0fGetRepoResponse\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\x12\x18\n" +
	"\acreator\x18\x03 \x01(\tR\acreator\x12\x1b\n" +
	"\tstars_cnt\x18\x04 \x01(\x05R\bstarsCnt\x12\x1b\n" +
	"\tforks_cnt\x18\x05 \x01(\x05R\bforksCnt\x12\x1d\n" +
	"\n" +
	"issues_cnt\x18\x06 \x01(\x05R\tissuesCnt\x12\x12\n" +
	"\x04lang\x18\a \x01(\tR\x04lang\x12\x12\n" +
	"\x04size\x18\b \x01(\x05R\x04size\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x18\n" +
	"\alicense\x18\n" +
	" \x01(\tR\alicense2E\n" +
	"\vRepoService\x126\n" +
	"\aGetRepo\x12\x14.repo.GetRepoRequest\x1a\x15.repo.GetRepoResponseB#Z!github.com/XRenso/barerepo/pkg/pbb\x06proto3"

var (
	file_repo_proto_rawDescOnce sync.Once
	file_repo_proto_rawDescData []byte
)

func file_repo_proto_rawDescGZIP() []byte {
	file_repo_proto_rawDescOnce.Do(func() {
		file_repo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)))
	})
	return file_repo_proto_rawDescData
}

var file_repo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_repo_proto_goTypes = []any{
	(*GetRepoRequest)(nil),  // 0: repo.GetRepoRequest
	(*GetRepoResponse)(nil), // 1: repo.GetRepoResponse
}
var file_repo_proto_depIdxs = []int32{
	0, // 0: repo.RepoService.GetRepo:input_type -> repo.GetRepoRequest
	1, // 1: repo.RepoService.GetRepo:output_type -> repo.GetRepoResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_repo_proto_init() }
func file_repo_proto_init() {
	if File_repo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_repo_proto_rawDesc), len(file_repo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_repo_proto_goTypes,
		DependencyIndexes: file_repo_proto_depIdxs,
		MessageInfos:      file_repo_proto_msgTypes,
	}.Build()
	File_repo_proto = out.File
	file_repo_proto_goTypes = nil
	file_repo_proto_depIdxs = nil
}
